services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=default.local  # Set a default host in case something goes wrong
      - VIRTUAL_HOST=atomacloud.com
      - VIRTUAL_PORT=3000            # Port of the Next.js app inside the container
      - ENABLE_IPV6=true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  # Allow the container to listen to Docker events
      - ./nginx/certs:/etc/nginx/certs            # Store certificates here
    ports:
      - "80:80"   # HTTP port
      - "443:443" # HTTPS port

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt       # Store certs in the shared volume
      - ./nginx/certbot/conf:/etc/letsencrypt/live  # Shared Certbot configurations
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: yourdomain.com
      VIRTUAL_PORT: 3000
    expose:
      - "3000"  # Expose port 3000, but don't publish it externally

networks:
  atoma-dashboard-network:
    driver: bridge
