export const LOCAL_STORAGE_SECRET_KEY = "ZKLOGIN-SECRET_KEY";
export const LOCAL_STORAGE_RANDOMNESS = "ZKLOGIN-RANDOMNESS";
export const LOCAL_STORAGE_MAX_EPOCH = "ZKLOGIN-MAX_EPOCH";
export const LOCAL_STORAGE_ZKP = "ZKLOGIN-ZKP";
export const LOCAL_STORAGE_ID_TOKEN = "id_token";
export const SUI_RPC_URL = process.env.NEXT_PUBLIC_SUI_RPC_URL;
export const PROVER_URL = process.env.NEXT_PUBLIC_PROVER_URL;
export const LOCAL_STORAGE_ACCESS_TOKEN = "access_token";
